In [1]:
import numpy as np

The Basics

In [2]:
a = np.array([1,2,3], dtype='int32')
a  #output

array([1, 2, 3])

In [3]:
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]]) #2D arrays
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
#Get Dimension a
a.ndim

1

In [6]:
#Get Dimension b
b.ndim

2

In [7]:
#get shape a (rows, columns)
a.shape

(3,)

In [8]:
#get shape b (rows, columns)
b.shape

(2, 3)

In [9]:
#get type
a.dtype

dtype('int32')

In [10]:
#get size (2 bytes-> int16 or 4 bytes -> int32)
a.itemsize

4

In [11]:
#get total size
a.size * a.itemsize

12

In [12]:
#get total size
a.nbytes

12

In [13]:
b.itemsize

8

Accessing/Changing specific elements, rows, columns, etc

In [14]:
c = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13,14]])
print(c)  #output
print('')
print(c.shape) #getshape
print('')
print(c.ndim)  #get Dimension

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

(2, 7)

2


In [15]:
#get a specific element [row, column]
c[1, 5]

13

In [16]:
c[1, -2]  # -1 = 14, -2 = 13

13

In [17]:
#get a specific row   (: --> slice)
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
#get a specific column
c[: , 2]

array([ 3, 10])

In [19]:
#getting a more fancy [startIndex: endIndex: stepsize]
# [row, start element: end element(will be excluded): step size]
c[0, 1:6:2]

array([2, 4, 6])

In [20]:
c[0, 1:-2:2]

array([2, 4])

In [21]:
c[0, 1:-1:2]

array([2, 4, 6])

In [22]:
c[1,5] = 20
print(c)
print('')
c[:,2] = 5
print(c)
print('')
c[:,2] = [1,2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-Dimension Example

In [23]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
#get specific element(work outside in)
d[0,1,1]

4

In [25]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [26]:
d[:,0,:]

array([[1, 2],
       [5, 6]])

In [27]:
d[:,0,0]

array([1, 5])

In [29]:
#replace
d[:,1,:] = [[9,9], [8,8]]
d

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initializing Different Types of Arrays

In [30]:
#All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [34]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [35]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [36]:
#any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [37]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)