In [410]:
import numpy as np

The Basics

In [411]:
a = np.array([1,2,3], dtype='int32')
a  #output

array([1, 2, 3])

In [412]:
print(a)

[1 2 3]


In [413]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]]) #2D arrays
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [414]:
#Get Dimension a
a.ndim

1

In [415]:
#Get Dimension b
b.ndim

2

In [416]:
#get shape a (rows, columns)
a.shape

(3,)

In [417]:
#get shape b (rows, columns)
b.shape

(2, 3)

In [418]:
#get type
a.dtype

dtype('int32')

In [419]:
#get size (2 bytes-> int16 or 4 bytes -> int32)
a.itemsize

4

In [420]:
#get total size
a.size * a.itemsize

12

In [421]:
#get total size
a.nbytes

12

In [422]:
b.itemsize

8

Accessing/Changing specific elements, rows, columns, etc

In [423]:
c = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13,14]])
print(c)  #output
print('')
print(c.shape) #getshape
print('')
print(c.ndim)  #get Dimension

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

(2, 7)

2


In [424]:
#get a specific element [row, column]
c[1, 5]

13

In [425]:
c[1, -2]  # -1 = 14, -2 = 13

13

In [426]:
#get a specific row   (: --> slice)
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [427]:
#get a specific column
c[: , 2]

array([ 3, 10])

In [428]:
#getting a more fancy [startIndex: endIndex: stepsize]
# [row, start element: end element(will be excluded): step size]
c[0, 1:6:2]

array([2, 4, 6])

In [429]:
c[0, 1:-2:2]

array([2, 4])

In [430]:
c[0, 1:-1:2]

array([2, 4, 6])

In [431]:
c[1,5] = 20
print(c)
print('')
c[:,2] = 5
print(c)
print('')
c[:,2] = [1,2]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-Dimension Example

In [432]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [433]:
#get specific element(work outside in)
d[0,1,1]

4

In [434]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [435]:
d[:,0,:]

array([[1, 2],
       [5, 6]])

In [436]:
d[:,0,0]

array([1, 5])

In [437]:
#replace
d[:,1,:] = [[9,9], [8,8]]
d

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initializing Different Types of Arrays

In [438]:
#All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [439]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [440]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [441]:
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [442]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [443]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [444]:
#any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [445]:
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [446]:
#any other number(full_like)
np.full_like(c.shape, 4)

array([4, 4])

In [447]:
np.full_like(c, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [448]:
#Random decimal numbers
np.random.rand(4,2)

array([[0.11893242, 0.69759128],
       [0.78072587, 0.29248052],
       [0.58786107, 0.69311144],
       [0.54675174, 0.60638092]])

In [449]:
np.random.random_sample(c.shape)

array([[0.18124977, 0.76923402, 0.18521203, 0.52354686, 0.4470054 ,
        0.47496629, 0.5761918 ],
       [0.46601986, 0.02653851, 0.75622108, 0.6103618 , 0.90019092,
        0.41097935, 0.88972065]])

In [450]:
#Random Integer values
np.random.randint(7, size=(3,3))

array([[2, 1, 6],
       [2, 4, 6],
       [2, 6, 0]])

In [451]:
# 4 to 7 random in 3 x 3 dimension
np.random.randint(4,7, size=(3,3))

array([[6, 5, 5],
       [5, 6, 4],
       [5, 4, 4]])

In [452]:
# 4 to 7 random in 3 x 3 dimension
np.random.randint(-4,8, size=(3,3))

array([[ 1, -1,  4],
       [ 7,  1,  4],
       [ 2, -4,  3]])

In [453]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [454]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [455]:
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [456]:
r1 = np.repeat(arr,3, axis = 1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [457]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z # [rows (from-to), colums(from-to)]
# or [1:4, 1:4] , 4 is exclusive value
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
