#### Be careful when copying arrays

In [353]:
import numpy as np

In [354]:
a = np.array([1,2,3])
b = a.copy() #will copy the a to b, to make a remain same
b

array([1, 2, 3])

In [355]:
b[0] = 100
print(b)

[100   2   3]


In [356]:
print(a)

[1 2 3]


Mathematics

In [357]:
c = np.array([1,2,3,4])
print(c)

[1 2 3 4]


In [358]:
c + 2  # c += 2

array([3, 4, 5, 6])

In [359]:
c - 2

array([-1,  0,  1,  2])

In [360]:
c * 2

array([2, 4, 6, 8])

In [361]:
c / 2

array([0.5, 1. , 1.5, 2. ])

In [362]:
d = np.array([1,0,1,0])
c + d

array([2, 2, 4, 4])

In [363]:
c ** 2

array([ 1,  4,  9, 16])

In [364]:
#take the sin
np.sin(c)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [365]:
np.cos(c)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

more info (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc ....


#### Linear Algebra

In [366]:
e = np.ones((2,3))
print(e)

f = np.full((3,2), 2)
print(f)

np.matmul(e, f)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [367]:
#Find determinant
g = np.identity(3)
np.linalg.det(g)  #determinant

1.0

#### Statistics

In [368]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [369]:
np.min(stats, axis = 0) #giving low balue of row axis

array([1, 2, 3])

In [370]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [371]:
np.sum(stats)

21

In [372]:
np.sum(stats, axis = 0)

array([5, 7, 9])

#### Reorganizing Arrays

In [373]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [374]:
print(before.shape)

(2, 4)
