In [100]:
import numpy as np

The Basics

In [101]:
a = np.array([1,2,3], dtype='int32')
a  #output

array([1, 2, 3])

In [102]:
print(a)

[1 2 3]


In [103]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]]) #2D arrays
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [104]:
#Get Dimension a
a.ndim

1

In [105]:
#Get Dimension b
b.ndim

2

In [106]:
#get shape a (rows, columns)
a.shape

(3,)

In [107]:
#get shape b (rows, columns)
b.shape

(2, 3)

In [108]:
#get type
a.dtype

dtype('int32')

In [109]:
#get size (2 bytes-> int16 or 4 bytes -> int32)
a.itemsize

4

In [110]:
#get total size
a.size * a.itemsize

12

In [111]:
#get total size
a.nbytes

12

In [112]:
b.itemsize

8

Accessing/Changing specific elements, rows, columns, etc

In [113]:
c = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13,14]])
print(c)  #output
print('')
print(c.shape) #getshape
print('')
print(c.ndim)  #get Dimension

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

(2, 7)

2


In [114]:
#get a specific element [row, column]
c[1, 5]

13

In [115]:
c[1, -2]  # -1 = 14, -2 = 13

13

In [116]:
#get a specific row   (: --> slice)
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [117]:
#get a specific column
c[: , 2]

array([ 3, 10])