#### Be careful when copying arrays

In [11]:
import numpy as np

In [12]:
a = np.array([1,2,3])
b = a
b

array([1, 2, 3])

In [13]:
b[0] = 100
print(b)

[100   2   3]


In [14]:
print(a)

[100   2   3]
