#### Be careful when copying arrays

In [47]:
import numpy as np

In [48]:
a = np.array([1,2,3])
b = a.copy() #will copy the a to b, to make a remain same
b

array([1, 2, 3])

In [49]:
b[0] = 100
print(b)

[100   2   3]


In [50]:
print(a)

[1 2 3]


Mathematics

In [51]:
c = np.array([1,2,3,4])
print(c)

[1 2 3 4]


In [52]:
c + 2  # c += 2

array([3, 4, 5, 6])

In [53]:
c - 2

array([-1,  0,  1,  2])

In [54]:
c * 2

array([2, 4, 6, 8])

In [55]:
c / 2

array([0.5, 1. , 1.5, 2. ])

In [56]:
d = np.array([1,0,1,0])
c + d

array([2, 2, 4, 4])