#### Be careful when copying arrays

In [334]:
import numpy as np

In [335]:
a = np.array([1,2,3])
b = a.copy() #will copy the a to b, to make a remain same
b

array([1, 2, 3])

In [336]:
b[0] = 100
print(b)

[100   2   3]


In [337]:
print(a)

[1 2 3]


Mathematics

In [338]:
c = np.array([1,2,3,4])
print(c)

[1 2 3 4]


In [339]:
c + 2  # c += 2

array([3, 4, 5, 6])

In [340]:
c - 2

array([-1,  0,  1,  2])

In [341]:
c * 2

array([2, 4, 6, 8])

In [342]:
c / 2

array([0.5, 1. , 1.5, 2. ])

In [343]:
d = np.array([1,0,1,0])
c + d

array([2, 2, 4, 4])

In [344]:
c ** 2

array([ 1,  4,  9, 16])

In [345]:
#take the sin
np.sin(c)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [346]:
np.cos(c)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

more info (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc ....


#### Linear Algebra

In [347]:
e = np.ones((2,3))
print(e)

f = np.full((3,2), 2)
print(f)

np.matmul(e, f)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [348]:
#Find determinant
g = np.identity(3)
np.linalg.det(g)  #determinant

1.0

#### Statistics

In [349]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [350]:
np.min(stats, axis = 0) #giving low balue of row axis

array([1, 2, 3])

In [351]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [352]:
np.sum(stats)

21