#### Be careful when copying arrays

In [23]:
import numpy as np

In [24]:
a = np.array([1,2,3])
b = a.copy() #will copy the a to b, to make a remain same
b

array([1, 2, 3])

In [25]:
b[0] = 100
print(b)

[100   2   3]


In [26]:
print(a)

[1 2 3]


Mathematics

stop at 35.59