In [51]:
import numpy as np

The Basics

In [52]:
a = np.array([1,2,3], dtype='int32')
a  #output

array([1, 2, 3], dtype=int16)

In [53]:
print(a)

[1 2 3]


In [54]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]]) #2D arrays
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [55]:
#Get Dimension a
a.ndim

1

In [56]:
#Get Dimension b
b.ndim

2

In [57]:
#get shape a (rows, columns)
a.shape

(3,)

In [58]:
#get shape b (rows, columns)
b.shape

(2, 3)

In [59]:
#get type
a.dtype

dtype('int16')

In [60]:
#get size (2 bytes-> int16 or 4 bytes -> int32)
a.itemsize

2