In [120]:
import numpy as np

The Basics

In [121]:
a = np.array([1,2,3], dtype='int32')
a  #output

array([1, 2, 3])

In [122]:
print(a)

[1 2 3]


In [123]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]]) #2D arrays
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [124]:
#Get Dimension a
a.ndim

1

In [125]:
#Get Dimension b
b.ndim

2

In [126]:
#get shape a (rows, columns)
a.shape

(3,)

In [127]:
#get shape b (rows, columns)
b.shape

(2, 3)

In [128]:
#get type
a.dtype

dtype('int32')

In [129]:
#get size (2 bytes-> int16 or 4 bytes -> int32)
a.itemsize

4

In [130]:
#get total size
a.size * a.itemsize

12

In [131]:
#get total size
a.nbytes

12

In [132]:
b.itemsize

8

Accessing/Changing specific elements, rows, columns, etc

In [133]:
c = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13,14]])
print(c)  #output
print('')
print(c.shape) #getshape
print('')
print(c.ndim)  #get Dimension

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

(2, 7)

2


In [134]:
#get a specific element [row, column]
c[1, 5]

13

In [135]:
c[1, -2]  # -1 = 14, -2 = 13

13

In [136]:
#get a specific row   (: --> slice)
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [137]:
#get a specific column
c[: , 2]

array([ 3, 10])

In [138]:
#getting a more fancy [startIndex: endIndex: stepsize]
# [row, start element: end element(will be excluded): step size]
c[0, 1:6:2]

array([2, 4, 6])