In [4]:
import numpy as np

The Basics

In [5]:
a = np.array([1,2,3])
a  #output

array([1, 2, 3])

In [6]:
print(a)

[1 2 3]


In [7]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]]) #2D arrays
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
#Get Dimension a
a.ndim

2

In [ ]:
#Get Dimension b
b.ndim