#### Be careful when copying arrays

In [518]:
import numpy as np

In [519]:
a = np.array([1,2,3])
b = a.copy() #will copy the a to b, to make a remain same
b

array([1, 2, 3])

In [520]:
b[0] = 100
print(b)

[100   2   3]


In [521]:
print(a)

[1 2 3]


Mathematics

In [522]:
c = np.array([1,2,3,4])
print(c)

[1 2 3 4]


In [523]:
c + 2  # c += 2

array([3, 4, 5, 6])

In [524]:
c - 2

array([-1,  0,  1,  2])

In [525]:
c * 2

array([2, 4, 6, 8])

In [526]:
c / 2

array([0.5, 1. , 1.5, 2. ])

In [527]:
d = np.array([1,0,1,0])
c + d

array([2, 2, 4, 4])

In [528]:
c ** 2

array([ 1,  4,  9, 16])

In [529]:
#take the sin
np.sin(c)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [530]:
np.cos(c)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

more info (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc ....


#### Linear Algebra

In [531]:
e = np.ones((2,3))
print(e)

f = np.full((3,2), 2)
print(f)

np.matmul(e, f)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [532]:
#Find determinant
g = np.identity(3)
np.linalg.det(g)  #determinant

1.0

#### Statistics

In [533]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [534]:
np.min(stats, axis = 0) #giving low balue of row axis

array([1, 2, 3])

In [535]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [536]:
np.sum(stats)

21

In [537]:
np.sum(stats, axis = 0)

array([5, 7, 9])

#### Reorganizing Arrays

In [538]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [539]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [540]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [541]:
print(before.shape)

(2, 4)


In [542]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [543]:
# horizontal stack
h1 = np.ones([2,4])
h2 = np.zeros([2,2])

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])