#### Be careful when copying arrays

In [161]:
import numpy as np

In [162]:
a = np.array([1,2,3])
b = a.copy() #will copy the a to b, to make a remain same
b

array([1, 2, 3])

In [163]:
b[0] = 100
print(b)

[100   2   3]


In [164]:
print(a)

[1 2 3]


Mathematics

In [165]:
c = np.array([1,2,3,4])
print(c)

[1 2 3 4]


In [166]:
c + 2  # c += 2

array([3, 4, 5, 6])

In [167]:
c - 2

array([-1,  0,  1,  2])

In [168]:
c * 2

array([2, 4, 6, 8])

In [169]:
c / 2

array([0.5, 1. , 1.5, 2. ])

In [170]:
d = np.array([1,0,1,0])
c + d

array([2, 2, 4, 4])

In [171]:
c ** 2

array([ 1,  4,  9, 16])

In [172]:
#take the sin
np.sin(c)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [173]:
np.cos(c)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

more info (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc ....


#### Linear Algebra

In [174]:
e = np.ones((2,3))
print(e)

f = np.full((3,2), 2)
print(f)

np.matmul(e, f)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [175]:
#Find determinant
g = np.identity(3)
np.linalg.det(g)  #determinant

1.0