In [61]:
import numpy as np

The Basics

In [62]:
a = np.array([1,2,3], dtype='int32')
a  #output

array([1, 2, 3])

In [63]:
print(a)

[1 2 3]


In [64]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]]) #2D arrays
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [65]:
#Get Dimension a
a.ndim

1

In [66]:
#Get Dimension b
b.ndim

2

In [67]:
#get shape a (rows, columns)
a.shape

(3,)

In [68]:
#get shape b (rows, columns)
b.shape

(2, 3)

In [69]:
#get type
a.dtype

dtype('int32')

In [70]:
#get size (2 bytes-> int16 or 4 bytes -> int32)
a.itemsize

4

In [71]:
#get total size
a.size * a.itemsize

12

In [72]:
#get total size
a.nbytes

12

In [73]:
b.itemsize

8

Accessing/Changing specific elements, rows, columns, etc