#### Be careful when copying arrays

In [468]:
import numpy as np

In [469]:
a = np.array([1,2,3])
b = a.copy() #will copy the a to b, to make a remain same
b

array([1, 2, 3])

In [470]:
b[0] = 100
print(b)

[100   2   3]


In [471]:
print(a)

[1 2 3]


Mathematics

In [472]:
c = np.array([1,2,3,4])
print(c)

[1 2 3 4]


In [473]:
c + 2  # c += 2

array([3, 4, 5, 6])

In [474]:
c - 2

array([-1,  0,  1,  2])

In [475]:
c * 2

array([2, 4, 6, 8])

In [476]:
c / 2

array([0.5, 1. , 1.5, 2. ])

In [477]:
d = np.array([1,0,1,0])
c + d

array([2, 2, 4, 4])

In [478]:
c ** 2

array([ 1,  4,  9, 16])

In [479]:
#take the sin
np.sin(c)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [480]:
np.cos(c)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

more info (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

- Determinant
- Trace
- Singular Vector Decomposition
- Eigenvalues
- Matrix Norm
- Inverse
- Etc ....


#### Linear Algebra

In [481]:
e = np.ones((2,3))
print(e)

f = np.full((3,2), 2)
print(f)

np.matmul(e, f)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [482]:
#Find determinant
g = np.identity(3)
np.linalg.det(g)  #determinant

1.0

#### Statistics

In [483]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [484]:
np.min(stats, axis = 0) #giving low balue of row axis

array([1, 2, 3])

In [485]:
np.max(stats, axis = 0)

array([4, 5, 6])

In [486]:
np.sum(stats)

21

In [487]:
np.sum(stats, axis = 0)

array([5, 7, 9])

#### Reorganizing Arrays

In [488]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [489]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [490]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [491]:
print(before.shape)

(2, 4)


In [492]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])