#### Be careful when copying arrays

In [132]:
import numpy as np

In [133]:
a = np.array([1,2,3])
b = a.copy() #will copy the a to b, to make a remain same
b

array([1, 2, 3])

In [134]:
b[0] = 100
print(b)

[100   2   3]


In [135]:
print(a)

[1 2 3]


Mathematics

In [136]:
c = np.array([1,2,3,4])
print(c)

[1 2 3 4]


In [137]:
c + 2  # c += 2

array([3, 4, 5, 6])

In [138]:
c - 2

array([-1,  0,  1,  2])

In [139]:
c * 2

array([2, 4, 6, 8])

In [140]:
c / 2

array([0.5, 1. , 1.5, 2. ])

In [141]:
d = np.array([1,0,1,0])
c + d

array([2, 2, 4, 4])

In [142]:
c ** 2

array([ 1,  4,  9, 16])

In [143]:
#take the sin
np.sin(c)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [144]:
np.cos(c)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

more info (https://docs.scipy.org/doc/numpy/reference/routine.math.html)

#### Linear Algebra

In [145]:
e = np.ones((2,3))
print(e)

f = np.full((3,2), 2)
print(f)

np.matmul(e, f)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])