In [35]:
from numpy import random
import numpy as np

In [36]:
random.randint(1,1000)

362

In [37]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.array(range(1,10,2))

array([1, 3, 5, 7, 9])

zero array

In [39]:
np.zeros([5])

array([0., 0., 0., 0., 0.])

In [40]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

one array

In [41]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
c = np.array([1,2,5,32,75,32,56])

c.reshape(1,-1)

array([[ 1,  2,  5, 32, 75, 32, 56]])