In [12]:
from numpy import random
import numpy as np

In [13]:
random.randint(1,1000)

742

In [14]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.array(range(1,10,2))

array([1, 3, 5, 7, 9])

In [16]:
np.zeros([5])

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])