In [45]:
from numpy import random
import numpy as np

In [46]:
random.randint(1,1000)

201

In [47]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.array(range(1,10,2))

array([1, 3, 5, 7, 9])

zero array

In [49]:
np.zeros([5])

array([0., 0., 0., 0., 0.])

In [50]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

one array

In [51]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
c = np.array([1,2,5,32,75,32,56])

c.reshape(1,-1)

array([[ 1,  2,  5, 32, 75, 32, 56]])

In [53]:
ones = np.ones([5,5])
ones.reshape(1,-1)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.]])