In [19]:
from numpy import random
import numpy as np

In [20]:
random.randint(1,1000)

153

In [21]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.array(range(1,10,2))

array([1, 3, 5, 7, 9])

zero array

In [23]:
np.zeros([5])

array([0., 0., 0., 0., 0.])

In [24]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

one array

In [26]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])